FROM node:16-buster AS builder

WORKDIR /app

COPY backend/package*.json ./

RUN yarn install

COPY backend/ .

RUN yarn build

FROM node:16-buster

WORKDIR /app

COPY --from=builder /app ./

RUN yarn install --production

EXPOSE 4200

# Запускаем приложение
CMD ["yarn", "start:prod"]
