name: CI/CD for Next.js and NestJS with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images for Frontend (Next.js) and Backend (NestJS)
        run: |
          docker build -t my-next-app -f ./frontend/dockerfile .
          docker build -t my-nest-api -f ./backend/dockerfile .

      - name: Push Docker images to DockerHub
        run: |
          docker push my-next-app
          docker push my-nest-api
